function [th1dotdotc1,th2dotdotc1] = accelC1(I2,d2,g,m2,th1,th2)
%ACCELC1
%    [TH1DOTDOTC1,TH2DOTDOTC1] = ACCELC1(I2,D2,G,M2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    08-Mar-2017 15:56:14

th1dotdotc1 = 0.0;
if nargout > 1
    t2 = th1+th2;
    t3 = cos(t2);
    t4 = d2.^2;
    t5 = sin(t2);
    th2dotdotc1 = -(d2.*g.*m2.*t5)./(I2+m2.*t3.^2.*t4+m2.*t4.*t5.^2);
end
