function [c2slideofftip,c2slideoffjoint] = c2slideguard(l1,l2,th1,th2,x,y)
%C2SLIDEGUARD
%    [C2SLIDEOFFTIP,C2SLIDEOFFJOINT] = C2SLIDEGUARD(L1,L2,TH1,TH2,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    08-Mar-2017 15:57:10

t2 = th1+th2;
t3 = cos(t2);
t4 = cos(th1);
t5 = l1.*t4;
t6 = t5+y;
t7 = sin(t2);
t8 = sin(th1);
t9 = x-l1.*t8;
t10 = t7.*t9;
c2slideofftip = -l2+t10-t3.*t6;
if nargout > 1
    c2slideoffjoint = t10-t3.*t6;
end
