function out1 = energy(I1,I2,d1,d2,g,l1,m1,m2,th1,th2,th1dot,th2dot)
%ENERGY
%    OUT1 = ENERGY(I1,I2,D1,D2,G,L1,M1,M2,TH1,TH2,TH1DOT,TH2DOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    08-Mar-2017 15:57:11

t2 = th1+th2;
t3 = sin(t2);
t11 = sin(th1);
t4 = th1dot.*(d2.*t3+l1.*t11)+d2.*t3.*th2dot;
t5 = cos(t2);
t9 = cos(th1);
t12 = d2.*t5;
t13 = l1.*t9;
t14 = t12+t13;
t6 = t14.*th1dot+d2.*t5.*th2dot;
t7 = th1dot+th2dot;
t8 = th1dot.^2;
t10 = d1.^2;
out1 = I1.*t8.*(1.0./2.0)+m1.*(t8.*t9.^2.*t10+t8.*t10.*t11.^2).*(1.0./2.0)+I2.*t7.^2.*(1.0./2.0)+m2.*(t4.^2+t6.^2).*(1.0./2.0)-g.*m2.*t14-d1.*g.*m1.*t9;
