function [out1,out2] = link1col(I2,d2,l1,m2,rest,th1,th2,th1dot_0,th2dot_0)
%LINK1COL
%    [OUT1,OUT2] = LINK1COL(I2,D2,L1,M2,REST,TH1,TH2,TH1DOT_0,TH2DOT_0)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    08-Mar-2017 15:57:12

out1 = -rest.*th1dot_0;
if nargout > 1
    t4 = th1+th2;
    t2 = cos(t4);
    t3 = d2.^2;
    t5 = sin(t4);
    t6 = t2.^2;
    t7 = t5.^2;
    t8 = cos(th1);
    t9 = sin(th1);
    out2 = (I2.*th1dot_0+I2.*th2dot_0+I2.*rest.*th1dot_0+m2.*t3.*t6.*th1dot_0+m2.*t3.*t7.*th1dot_0+m2.*t3.*t6.*th2dot_0+m2.*t3.*t7.*th2dot_0+m2.*rest.*t3.*t6.*th1dot_0+m2.*rest.*t3.*t7.*th1dot_0+d2.*l1.*m2.*t2.*t8.*th1dot_0+d2.*l1.*m2.*t5.*t9.*th1dot_0+d2.*l1.*m2.*rest.*t2.*t8.*th1dot_0+d2.*l1.*m2.*rest.*t5.*t9.*th1dot_0)./(I2+m2.*t3.*t6+m2.*t3.*t7);
end
